version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: history
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

# This is the network created so that the docker images can connect to one another
networks:
  db_network:

services:

# This is the MySQL database that will store persisted data
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: 0.0.0.0
    networks:
      - db_network
    expose:
      - '3306'

# This is the backend API server that handles requests + database calls
  api:
    build:
      dockerfile: Dockerfile
      context: "./Backend"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./Backend:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - "3001:3001"
    networks:
      - db_network

# This is the front end webpage: the UI
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./titlebot
    volumes:
      - /app/node_modules
      - ./titlebot:/app
    ports:
      - "3000:3000"
    networks:
      - db_network

# Used to check Postgres database from the browser 
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
      networks:
      - db_network